// This file automatically Generated by Memory Organizer 
// By gxd -- All rights Reserved!

#define  SPLASHL_TIM  0x80090000
#define  SPLASHR_TIM  0x80099824
#define  GUI_TPAGE_TIM  0x800A3048
